# Generated by Django 2.0.2 on 2018-02-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('platforms', models.CharField(choices=[('one', 'choice_one'), ('two', 'choice_two'), ('three', 'choice_three')], default='one', max_length=225)),
                ('multiplayer', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images')),
            ],
        ),
    ]
