# Generated by Django 2.0.2 on 2018-02-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.CharField(choices=[('PC', 'PC'), ('PlayStation', 'PlayStation'), ('XBOX', 'XBOX')], max_length=100),
        ),
    ]
